# name: Deployment to Github Pages

# on:
#   push:
#     branches:
#       - "main"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.17]

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Install and build
#         run: npm install && npm run gh-build && cp docs/index.html docs/404.html

#       # - name: Deploy
#       #   uses: JamesIves/github-pages-deploy-action@4.1.1
#       #   with:
#       #     branch: gh-pages #The branch the action should deploy to.
#       #     folder: docs #The folder the action should deploy.

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: dist/paynet
          enable_jekyll: true
